name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Fix build files
        run: |
          sed -i '/ndkVersion/d' app/build.gradle
          sed -i '/ndk {/,/}/d' app/build.gradle
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "ndk.dir=" >> local.properties
          unset ANDROID_NDK_HOME
      - name: Build
        run: |
          unset ANDROID_NDK_HOME
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kode-in-debug
          path: app/build/outputs/apk/debug/app-debug.apk
